language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
dist: trusty
services: postgresql
addons:
  postgresql: 9.4
env:
  global:
    - TAIMIO_DBNAME=taimio
    - TAIMIO_USERNAME=postgres
install: composer install
before_script: cp phinx.yml.travis phinx.yml
script: composer test
